### PR TITLE
Add UE_LOG to Macros that will not generate indent on the next line

### PR DESCRIPTION
**Pull request by AlKoulounil**
Hi ! I'm proposing to add UE_LOG into the list of macros in the regular expression. I've already tested it on my side and works well.

### CODE REVIEW

**Comment by hackalyze** [comment]
Looks good to me, could you also add UE_LOG to the list in the readme?

**Comment by AlKoulounil** [comment]
Looks like you already did it ;).

**Comment by hackalyze** [comment]
Yes, thanks for the PR!

**Comment by hackalyze** [comment]
Hi @AlKoulounil, I ended up reverting this change to fix https://github.com/hackalyze/ue4-vs-extensions/issues/19

I found when testing UE_LOG that there didn't seem to be any indentation issues with that particular macro with this extension disabled, and so it seemed to me like the addition of UE_LOG support here was unnecessary.  The reason being the macro is terminated with a semicolon, unlike other macros like UFUCTION().  If you have an example you could show me where the use of UE_LOG causes indentation issues you need resolved through the use of this extension, could you provide an example?  It may be that I need to fix the extension to work with macros that are terminated by a semicolon, but it would be nice to have a real example in-hand.  Thanks!

**Pull request merged**
